In [2]:
from d2l import torch as d2l 
import numpy as np
import torch
from torch.utils import data 

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a PyTorch data iterator."""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

[tensor([[ 1.3837,  1.3505],
         [-0.5149,  0.5257],
         [-1.4392,  1.8043],
         [ 0.9785, -0.1251],
         [ 0.0644, -0.8518],
         [-0.1513, -0.0997],
         [ 1.0674,  0.1059],
         [-0.1346,  2.2118],
         [-0.8971,  0.0852],
         [ 0.1334, -1.5245]]),
 tensor([[ 2.3810],
         [ 1.3625],
         [-4.8072],
         [ 6.5704],
         [ 7.2283],
         [ 4.2502],
         [ 5.9724],
         [-3.5947],
         [ 2.1058],
         [ 9.6549]])]

In [4]:
# 'nn' is an abbreviation for neural networks
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))

In [5]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [6]:
loss = nn.MSELoss()

In [7]:
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)

In [8]:
num_epochs = 3 
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000309
epoch 2, loss 0.000102
epoch 3, loss 0.000102


In [9]:
print(net[0].weight.data)
print(net[0].bias.data)

w = net[0].weight.data
print('error in estimating w:', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('error in estimating b:', true_b - b)

tensor([[ 1.9997, -3.4003]])
tensor([4.1987])
error in estimating w: tensor([0.0003, 0.0003])
error in estimating b: tensor([0.0013])
